/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tcolligan_ecdhtest_ECDHLibrary */

#ifndef _Included_com_tcolligan_ecdhtest_ECDHLibrary
#define _Included_com_tcolligan_ecdhtest_ECDHLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tcolligan_ecdhtest_ECDHLibrary
 * Method:    generateKeyPair
 * Signature: ()Lcom/tcolligan/ecdhtest/ECDHKeyPair;
 */
JNIEXPORT jobject JNICALL Java_com_tcolligan_ecdhtest_ECDHLibrary_generateKeyPair
  (JNIEnv *, jclass);

/*
 * Class:     com_tcolligan_ecdhtest_ECDHLibrary
 * Method:    retrieveSharedSecret
 * Signature: ([B[B)Lcom/tcolligan/ecdhtest/SharedSecret;
 */
JNIEXPORT jobject JNICALL Java_com_tcolligan_ecdhtest_ECDHLibrary_retrieveSharedSecret
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_tcolligan_ecdhtest_ECDHLibrary
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tcolligan_ecdhtest_ECDHLibrary_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
